name: flutterhole
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # error handling using `Either<Failure, SuccessType>`
  dartz: ^0.9.1
  # service location
  get_it: ^4.0.2
  # dependency injection
  injectable: ^0.3.0
  # state management
  bloc: ^4.0.0
  provider: ^4.1.1
  # http client
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  # storage
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  # model annotation
  freezed_annotation: ^0.7.1
  json_annotation: ^3.0.1
  # routing
  sailor: ^0.7.1
  # internationalization
  intl: ^0.16.1

  # utilities
  supercharged: ^1.5.1
  flutter_bloc: ^4.0.0
  flutter_form_builder: ^3.9.0
  barcode_scan: ^3.0.1

  # ui sugar
  bottom_navy_bar: ^5.4.0
  flutter_vector_icons: ^0.2.1
  flutter_staggered_grid_view: ^0.3.0
  animations: ^1.0.0+5
  modal_bottom_sheet: ^0.1.5
  flutter_spinkit: ^4.1.2+1
  fl_chart: ^0.9.4
  flutter_sticky_header: ^0.4.2
  flushbar: ^1.10.2

  # log page
  alice: ^0.0.33

  # about page
  package_info: ^0.4.0+17
  qr_flutter: ^3.2.0
  share: ^0.6.4+1
  launch_review: ^2.0.0
  url_launcher: ^5.4.5
  flutter_markdown: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # code generation
  build_runner: ^1.9.0
  # data model & sealed union code generation
  freezed: ^0.10.8
  # generators
  injectable_generator: ^0.3.5
  # toJson/fromJson generator
  json_serializable: ^3.3.0
  # test stubbing
  mockito: ^4.1.1
  # bloc stubs & mocks
  bloc_test: ^5.1.0
  # fast, deterministic, and async timer tests
  fake_async: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
