---
name: flutterhole_web
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  settings_ui: ^1.0.0
  adaptive_dialog: ^1.0.0
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  intl: ^0.17.0
  package_info_plus: ^1.0.2
  url_launcher: ^6.0.3
  freezed_annotation: ^0.14.2
  dartz: ^0.10.0-nullsafety.2
  flutter_staggered_grid_view: ^0.4.0
  html: ^0.15.0
  animations: ^2.0.0
  pull_to_refresh: ^2.0.0
  fl_chart: ^0.36.1
  implicitly_animated_reorderable_list: ^0.4.0
  faker: ^2.0.0-rc.2
  infinite_scroll_pagination: ^3.0.1+1
  google_fonts: ^2.1.0
  auto_route: ^2.2.0
  in_app_review: ^2.0.2
  shared_preferences: ^2.0.6
  qr_code_scanner: ^0.5.1
  logging: ^1.0.1
  timeago: ^3.1.0
  flutter_markdown: ^0.6.2
  animated_text_kit: ^4.2.1
dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  auto_route_generator: ^2.1.0
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.3
  lints: ^1.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
