---
name: flutterhole_web
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  dio: ^3.0.10
  flutter:
    sdk: flutter
  json_annotation: ^3.1.1
  settings_ui: ^0.5.0
  flutter_icons: ^1.1.0
  adaptive_dialog: ^0.9.3
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.2
  intl: ^0.16.1
  package_info: '>=0.4.3+2 <2.0.0'
  url_launcher: ^5.7.10
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  freezed_annotation: ^0.12.0
  dartz: ^0.9.2
  flutter_staggered_grid_view: ^0.3.3
dev_dependencies:
  build_runner: ^1.11.0
  flutter_test:
    sdk: flutter
  freezed: ^0.12.7
  hive_generator: ^0.8.2
  integration_test:
    sdk: flutter
  json_serializable: ^3.5.1
flutter:
  uses-material-design: true
