---
name: flutterhole_web
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
#  flutter: '^2.1.0'
dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1
  settings_ui: ^1.0.0
  adaptive_dialog: ^1.0.0
  flutter_hooks: ^0.17.0
  hooks_riverpod: ^0.14.0+4
  intl: ^0.17.0
  package_info_plus: ^1.0.1
  url_launcher: ^6.0.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  freezed_annotation: ^0.14.2
  dartz: ^0.10.0-nullsafety.2
  flutter_staggered_grid_view: ^0.4.0
  html: ^0.15.0
  animations: ^2.0.0
#  pull_to_refresh: ^1.6.5
  pull_to_refresh:
    git:
      url: https://github.com/peng8350/flutter_pulltorefresh.git
      ref: nullsafety
  syncfusion_flutter_charts: ^19.1.58
  implicitly_animated_reorderable_list: ^0.4.0
  faker: ^2.0.0-rc.2
  infinite_scroll_pagination: ^3.0.1
  google_fonts: ^2.1.0
dev_dependencies:
  build_runner: ^2.0.4
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  hive_generator: ^1.1.0
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.3
flutter:
  uses-material-design: true
